default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER', 'mysql2') %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  database: <%= ENV.fetch('DB', 'test_task') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: <%= ENV.fetch('DB_HOST', '0.0.0.0') %>
  port: <%= ENV.fetch('DB_PORT', 3306) %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default
  database: 'test_task_test'

production:
  <<: *default
  sslverify: <%= ENV['DB_SSL_VERIFY'] || 'false' %>
